### ISSUE TITLE
Some insights on how to plot dggridR grids on a earth sphere?

### ISSUE THREAD

**Issue by damaha** [r-barnes/dggridR#1]
Hi,

I downloaded and installed dggridR, and I am very pleased about how easy it was to install and summarize my data in a grid. 

My next problem is plotting though and it probably due to my lack of experience with Geodesic Discrete Global Grid Systems, but could there be some example code in the README.md to show how to plot the second figure ("You data could look like this")?

/David

**Comment by r-barnes** [comment]
David,
This should be better documented, but please type "browseVignettes()" in R
and look for the dggridR directory. It will have many examples. This is
also a great way to find examples for other packages as well.

Cheers,
Richard

On Jul 19, 2016 8:08 AM, "damaha" <notifications@github.com> wrote:

Hi,

I downloaded and installed dggridR, and I am very pleased about how easy it
was to install and summarize my data in a grid.

My next problem is plotting though and it probably due to my lack of
experience with Geodesic Discrete Global Grid Systems, but could there be
some example code in the README.md to show how to plot the second figure
("You data could look like this")?

/David

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/r-barnes/dggridR/issues/1>, or mute the thread

**Comment by damaha** [comment]
Thanks for the quick reply! It was very helpful.

**Comment by r-barnes** [comment]
I've added a note about `browseVignettes()` to the read me. Thanks for pointing this out!
